language: python
python:
    - 3.5
branches:
    only:
    - feature_travis

install:
    - pip install --upgrade pipenv
    - pipenv install --three --dev
    - pipenv install django==1.8.18 

script:
    - pipenv run pytest
