# Generated by Django 2.0.8 on 2018-08-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0005_auto_20180703_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='conselhocultural',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criacaosistema',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundocultura',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgaogestor',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planocultura',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
