# Generated by Django 2.0.8 on 2019-03-29 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0025_auto_20190320_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivocomponente2',
            name='diligencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivo', to='gestao.DiligenciaSimples'),
        ),
    ]
