# Generated by Django 2.0.8 on 2019-04-02 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0029_auto_20190402_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivocomponente2',
            name='diligencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='componente', to='gestao.DiligenciaSimples'),
        ),
    ]
