# Generated by Django 2.0.8 on 2019-04-12 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0029_auto_20190402_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundodecultura',
            name='comprovante_cnpj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes', to='planotrabalho.ArquivoComponente2'),
        ),
        migrations.AddField(
            model_name='historicalfundodecultura',
            name='comprovante_cnpj',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='planotrabalho.ArquivoComponente2'),
        ),
    ]
