# Generated by Django 2.0.8 on 2019-04-08 20:32

from django.db import migrations, models
import planotrabalho.models


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0030_auto_20190402_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundodecultura',
            name='comprovante_cnpj',
            field=models.FileField(blank=True, null=True, upload_to=planotrabalho.models.upload_to),
        ),
        migrations.AddField(
            model_name='historicalfundodecultura',
            name='comprovante_cnpj',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
