# Generated by Django 2.0.8 on 2019-04-22 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0030_auto_20190412_1405'),
        ('planotrabalho', '0030_auto_20190402_1805'),
    ]

    operations = [
    ]
