# Generated by Django 2.0.8 on 2019-04-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0013_auto_20190211_1446'),
        ('planotrabalho', '0030_auto_20190402_1805'),
    ]

    operations = [
    ]
