# Generated by Django 2.0.8 on 2019-04-25 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0031_merge_20190422_1653'),
        ('planotrabalho', '0031_merge_20190416_1628'),
    ]

    operations = [
    ]
