# Generated by Django 2.0.8 on 2019-05-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0031_merge_20190422_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='conselhodecultura',
            name='exclusivo_cultura',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conselhodecultura',
            name='paritario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalconselhodecultura',
            name='exclusivo_cultura',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalconselhodecultura',
            name='paritario',
            field=models.BooleanField(default=False),
        ),
    ]
