# Generated by Django 2.0.8 on 2019-05-07 19:36

from django.db import migrations

def migra_orgao_gestor(apps, schema_editor):
    Componente = apps.get_model('planotrabalho', 'Componente')
    OrgaoGestor2 = apps.get_model('planotrabalho', 'OrgaoGestor2')

    ORGAO_GESTOR = 1
    for componente in Componente.objects.filter(tipo=ORGAO_GESTOR):
        orgao = OrgaoGestor2()
        orgao.componente_ptr = componente
        orgao.save()

        componente.orgaogestor2 = orgao
        componente.save()


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0032_historicalorgaogestor2_orgaogestor2'),
    ]

    operations = [
        migrations.RunPython(migra_orgao_gestor)
    ]
