# Generated by Django 2.0.8 on 2019-05-10 20:08

from django.db import migrations
from planotrabalho.models import Componente

def mudar_situacao_componetes (apps, schema_editor):

    for trocaSituacao in Componente.objects.exclude(arquivo=None).filter(situacao=0):
        trocaSituacao.tipo = 1
        trocaSituacao.save()

class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0033_auto_20190507_1636'),
    ]

    operations = [
      migrations.RunPython(mudar_situacao_componetes)  
    ]
