# Generated by Django 2.0.8 on 2019-05-10 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0033_auto_20190507_1636'),
    ]

    operations = [
    ]
