# Generated by Django 2.0.8 on 2019-05-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0033_auto_20190507_1636'),
        ('planotrabalho', '0032_auto_20190507_1913'),
    ]

    operations = [
    ]
