# Generated by Django 2.0.8 on 2019-05-22 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0034_merge_20190521_1547'),
        ('planotrabalho', '0034_merge_20190510_1412'),
        ('planotrabalho', '0034_auto_20190510_1722'),
    ]

    operations = [
    ]
