# Generated by Django 2.0.8 on 2019-06-04 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0037_auto_20190604_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalplanodecultura',
            old_name='ano_curso',
            new_name='ano_inicio_curso',
        ),
        migrations.RenameField(
            model_name='planodecultura',
            old_name='ano_curso',
            new_name='ano_inicio_curso',
        ),
        migrations.AddField(
            model_name='historicalplanodecultura',
            name='ano_termino_curso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planodecultura',
            name='ano_termino_curso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
