# Generated by Django 2.0.8 on 2019-07-29 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0039_auto_20190611_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conselheiro',
            name='conselho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planotrabalho.ConselhoDeCultura'),
        ),
        migrations.AlterField(
            model_name='historicalorgaogestor2',
            name='perfil',
            field=models.IntegerField(blank=True, choices=[('', 'Selecione um perfil'), (0, 'Não possui estrutura'), (1, 'Órgão da administração indireta'), (2, 'Secretaria em conjunto com outras políticas'), (3, 'Secretaria exclusiva de cultura'), (4, 'Setor subordinado à chefia do Executivo'), (5, 'Setor subordinado à outra secretaria')], null=True),
        ),
        migrations.AlterField(
            model_name='orgaogestor2',
            name='perfil',
            field=models.IntegerField(blank=True, choices=[('', 'Selecione um perfil'), (0, 'Não possui estrutura'), (1, 'Órgão da administração indireta'), (2, 'Secretaria em conjunto com outras políticas'), (3, 'Secretaria exclusiva de cultura'), (4, 'Setor subordinado à chefia do Executivo'), (5, 'Setor subordinado à outra secretaria')], null=True),
        ),
    ]
