# Generated by Django 2.0.8 on 2020-07-05 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0040_auto_20190729_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorgaogestor2',
            name='agencia',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='historicalorgaogestor2',
            name='banco',
            field=models.CharField(blank=True, choices=[(0, '001 - BANCODO BRASIL S.A'), (1, '104 - CAIXA ECONOMICA FEDERAL')], max_length=20, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='historicalorgaogestor2',
            name='cnpj',
            field=models.CharField(blank=True, default=None, max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='historicalorgaogestor2',
            name='comprovante_cnpj',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='planotrabalho.ArquivoComponente2'),
        ),
        migrations.AddField(
            model_name='historicalorgaogestor2',
            name='conta',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Conta Corrente com dígito'),
        ),
        migrations.AddField(
            model_name='orgaogestor2',
            name='agencia',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='orgaogestor2',
            name='banco',
            field=models.CharField(blank=True, choices=[(0, '001 - BANCODO BRASIL S.A'), (1, '104 - CAIXA ECONOMICA FEDERAL')], max_length=20, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='orgaogestor2',
            name='cnpj',
            field=models.CharField(blank=True, default=None, max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='orgaogestor2',
            name='comprovante_cnpj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes_orgao_gestor', to='planotrabalho.ArquivoComponente2'),
        ),
        migrations.AddField(
            model_name='orgaogestor2',
            name='conta',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Conta Corrente com dígito'),
        ),
    ]
