# Generated by Django 2.0.8 on 2020-07-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0044_auto_20200708_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundodecultura',
            name='agencia',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='fundodecultura',
            name='banco',
            field=models.CharField(blank=True, choices=[(0, '001 - BANCODO BRASIL S.A'), (1, '104 - CAIXA ECONOMICA FEDERAL')], max_length=20, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='fundodecultura',
            name='conta',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Conta Corrente com dígito'),
        ),
        migrations.AddField(
            model_name='historicalfundodecultura',
            name='agencia',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='historicalfundodecultura',
            name='banco',
            field=models.CharField(blank=True, choices=[(0, '001 - BANCODO BRASIL S.A'), (1, '104 - CAIXA ECONOMICA FEDERAL')], max_length=20, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='historicalfundodecultura',
            name='conta',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Conta Corrente com dígito'),
        ),
    ]
