# Generated by Django 2.0.8 on 2020-07-19 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0046_auto_20200717_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgaogestor2',
            name='comprovante_cnpj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes_cnpj', to='planotrabalho.ArquivoComponente2'),
        ),
    ]
