# Generated by Django 2.0.8 on 2019-04-04 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0038_usuario_email_pessoal'),
        ('adesao', '0038_auto_20190325_1731'),
    ]

    operations = [
    ]
