# Generated by Django 2.0.8 on 2019-04-22 20:56

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0039_merge_20190404_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='tipo_funcionario',
            field=models.IntegerField(choices=[(0, 'Gestor de Cultura'), (1, 'Responsável'), (2, 'Gestor')], default='0'),
        ),
    ]
