# Generated by Django 2.0.8 on 2019-04-22 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0040_auto_20190422_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sistemacultura',
            old_name='secretario',
            new_name='gestor_cultura',
        ),
        migrations.RemoveField(
            model_name='sistemacultura',
            name='responsavel',
        ),
    ]
