# Generated by Django 2.0.8 on 2019-04-22 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0041_auto_20190422_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemacultura',
            name='gestor_cultura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sistema_cultura_gestor_cultura', to='adesao.Funcionario'),
        ),
    ]
