# Generated by Django 2.0.8 on 2019-05-07 19:51

from django.db import migrations, models
import django.db.models.deletion

def copia_orgaos(apps, schema_editor):
    SistemaCultura = apps.get_model('adesao', 'SistemaCultura')
    for sistema in SistemaCultura.objects.filter(orgao_gestor__tipo=1):
        sistema.orgao_aux = sistema.orgao_gestor.orgaogestor2
        sistema.save()


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0033_auto_20190507_1636'),
        ('adesao', '0042_auto_20190422_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemacultura',
            name='orgao_aux',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orgao_aux', to='planotrabalho.OrgaoGestor2'),
        ),
        migrations.RunPython(copia_orgaos),
        migrations.RemoveField(
            model_name='sistemacultura',
            name='orgao_gestor',
        ),
        migrations.RenameField(
            model_name='sistemacultura',
            old_name='orgao_aux',
            new_name='orgao_gestor',
        ),
    ]
