# Generated by Django 2.0.8 on 2019-05-07 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0043_auto_20190507_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemacultura',
            name='orgao_gestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orgao_gestor', to='planotrabalho.OrgaoGestor2'),
        ),
    ]
