# Generated by Django 2.0.8 on 2019-06-11 17:14

from django.db import migrations, models
import django.db.models.deletion

def copia_planos(apps, schema_editor):
    SistemaCultura = apps.get_model('adesao', 'SistemaCultura')
    for sistema in SistemaCultura.objects.filter(plano__tipo=4):
        sistema.plano_aux = sistema.plano.planodecultura
        sistema.save()


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0044_auto_20190507_1709'),
        ('planotrabalho', '0039_auto_20190611_1335')
    ]

    operations = [
        migrations.AddField(
            model_name='sistemacultura',
            name='plano_aux',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plano_aux', to='planotrabalho.PlanoDeCultura'),
        ),
        migrations.RunPython(copia_planos),
        migrations.RemoveField(
            model_name='sistemacultura',
            name='plano',
        ),
        migrations.RenameField(
            model_name='sistemacultura',
            old_name='plano_aux',
            new_name='plano',
        ),
    ]
