# Generated by Django 2.0.8 on 2019-07-16 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adesao', '0045_auto_20190611_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlteracaoDeCadastrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alterado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Alterado em')),
                ('alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sistemas_cadastrador_alterado', to='adesao.Usuario')),
                ('cadastrador_antigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracao_antigos', to='adesao.Usuario')),
                ('cadastrador_novo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracao_novos', to='adesao.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAlteracaoDeCadastrador',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('alterado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Alterado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('alterado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='adesao.Usuario')),
                ('cadastrador_antigo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='adesao.Usuario')),
                ('cadastrador_novo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='adesao.Usuario')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical alteracao de cadastrador',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='sistemacultura',
            name='alteracao_cadastrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_cadastrador', to='adesao.AlteracaoDeCadastrador'),
        ),
    ]
