# Generated by Django 2.0.8 on 2019-07-29 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0045_auto_20190611_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemacultura',
            name='oficio_cadastrador',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='oficio_cadastrador'),
        ),
        migrations.AlterField(
            model_name='sistemacultura',
            name='plano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plano', to='planotrabalho.PlanoDeCultura'),
        ),
    ]
