# Generated by Django 2.0.8 on 2019-07-12 21:00

from django.db import migrations


def copia_alteracoes(apps, schema_editor):
    SistemaCultura = apps.get_model('adesao', 'SistemaCultura')
    AlteracaoDeCadastrador = apps.get_model('adesao', 'AlteracaoDeCadastrador')
    for sistema in SistemaCultura.objects.distinct('ente_federado'):
        ente_historico = SistemaCultura.historico.ente(sistema.ente_federado.cod_ibge)
        sistema_base = sistemas.first()

        for sistema in sistemas:
            if sistema.cadastrador != sistema_base.cadastrador:
                alteracao = AlteracaoDeCadastrador.objects.create(cadastrador_antigo=sistema_base.cadastrador,
                    cadastrador_novo=sistema.cadastrador, alterado_em=sistema.alterado_em,
                    alterado_por=sistema.alterado_por)
                sistema.alteracao.add(alteracao)


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0046_auto_20190712_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemacultura',
            name='alteracao_cadastrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_cadastrador', to='adesao.AlteracaoDeCadastrador'),
        ),
        migrations.RunPython(copia_alteracoes),
    ]
