# Generated by Django 2.0.8 on 2019-07-12 21:00

from django.db import migrations, models
import django.db.models.deletion


def copia_alteracoes(apps, schema_editor):
    SistemaCultura = apps.get_model('adesao', 'SistemaCultura')
    AlteracaoDeCadastrador = apps.get_model('adesao', 'AlteracaoDeCadastrador')
    for sistema in SistemaCultura.objects.distinct('ente_federado').order_by('ente_federado'):
        if sistema.ente_federado:
            ente_historico = SistemaCultura.objects.filter(
                ente_federado__cod_ibge=sistema.ente_federado.cod_ibge).order_by('alterado_em')
            sistema_base = ente_historico.first()

            for sistema in ente_historico:
                if sistema.cadastrador != sistema_base.cadastrador:
                    alteracao = AlteracaoDeCadastrador.objects.create(cadastrador_antigo=sistema_base.cadastrador,
                        cadastrador_novo=sistema.cadastrador, alterado_em=sistema.alterado_em,
                        alterado_por=sistema.alterado_por)
                    sistema.alteracao_cadastrador = alteracao
                    sistema.save()

                    sistema_base = sistema


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0046_auto_20190712_1611'),
    ]

    operations = [
        migrations.RunPython(copia_alteracoes),
    ]
