# Generated by Django 2.0.8 on 2019-07-12 21:00

from django.db import migrations, models
import django.db.models.deletion


def copia_alteracoes(apps, schema_editor):
    SistemaCultura = apps.get_model('adesao', 'SistemaCultura')
    AlteracaoDeCadastrador = apps.get_model('adesao', 'AlteracaoDeCadastrador')
    for sistema in SistemaCultura.objects.distinct('ente_federado').order_by('ente_federado'):
        if sistema.ente_federado:
            ente_historico = SistemaCultura.objects.filter(
                ente_federado__cod_ibge=sistema.ente_federado.cod_ibge).order_by('alterado_em')
            sistema_base = ente_historico.first()

            alteracao = AlteracaoDeCadastrador.objects.create(cadastrador_antigo=None,
                        cadastrador_novo=sistema_base.cadastrador, alterado_em=sistema_base.alterado_em,
                        alterado_por=sistema_base.alterado_por)
            sistema_base.alteracao_cadastrador = alteracao
            sistema_base.save()

            for sistema in ente_historico[1:]:
                if sistema.cadastrador != sistema_base.cadastrador:
                    sistema.alteracao_cadastrador = sistema_base.alteracao_cadastrador
                    sistema.alteracao_cadastrador.cadastrador_antigo = sistema_base.cadastrador
                    sistema.alteracao_cadastrador.cadastrador_novo = sistema.cadastrador
                    sistema.alteracao_cadastrador.alterado_em = sistema.alterado_em
                    sistema.alteracao_cadastrador.alterado_por = sistema.alterado_por
                else:
                    sistema.alteracao_cadastrador = sistema_base.alteracao_cadastrador

                sistema.alteracao_cadastrador.save()
                sistema.save()
                sistema_base = sistema


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0046_auto_20190716_1436'),
    ]

    operations = [
        migrations.RunPython(copia_alteracoes),
    ]
