# Generated by Django 2.0.8 on 2019-10-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0049_auto_20191008_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='estado_expeditor',
            field=models.IntegerField(choices=[(12, 'AC'), (27, 'AL'), (13, 'AM'), (16, 'AP'), (29, 'BA'), (23, 'CE'), (53, 'DF'), (32, 'ES'), (52, 'GO'), (21, 'MA'), (31, 'MG'), (50, 'MS'), (51, 'MT'), (15, 'PA'), (25, 'PB'), (26, 'PE'), (22, 'PI'), (41, 'PR'), (33, 'RJ'), (24, 'RN'), (11, 'RO'), (14, 'RR'), (43, 'RS'), (42, 'SC'), (28, 'SE'), (35, 'SP'), (17, 'TO')]),
        ),
    ]
