# Generated by Django 2.0.8 on 2019-10-08 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0050_auto_20191008_1815'),
        ('adesao', '0051_auto_20191008_1616'),
    ]

    operations = [
    ]
