# Generated by Django 2.0.8 on 2020-07-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0053_auto_20200211_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sede',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
