# Generated by Django 2.0.8 on 2020-07-19 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0055_requerimentotrocacadastrador_trocacadastrador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requerimentotrocacadastrador',
            name='ente_federado',
        ),
        migrations.DeleteModel(
            name='RequerimentoTrocaCadastrador',
        ),
    ]
