# Generated by Django 2.0.8 on 2020-07-18 21:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0055_requerimentotrocacadastrador_trocacadastrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoDeAdesao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('0', 'Pendente de Análise'), ('1', 'Aprovado'), ('2', 'Rejeitado')], default='0', max_length=1, null=True)),
                ('alterado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Alterado em')),
                ('oficio', models.FileField(max_length=255, null=True, upload_to='oficio')),
                ('laudo', models.TextField(blank=True, null=True)),
                ('alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adesao.Usuario')),
                ('ente_federado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adesao.EnteFederado')),
            ],
        ),
    ]
