# Generated by Django 2.0.8 on 2020-07-19 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0056_solicitacaodeadesao'),
        ('adesao', '0056_auto_20200719_1742'),
    ]

    operations = [
    ]
