# Generated by Django 2.0.8 on 2020-07-14 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0056_remove_requerimentotrocacadastrador_data_criacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrocaCadastrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(blank=True, choices=[('0', 'Aguardando preenchimento dos dados cadastrais'), ('1', 'Aguardando envio da documentação'), ('2', 'Aguardando renovação da adesão'), ('3', 'Diligência Documental'), ('4', 'Aguardando análise do Plano de Trabalho'), ('5', ''), ('6', 'Publicado no DOU'), ('7', '')], max_length=1, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='historico')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adesao.Usuario')),
            ],
        ),
    ]
