# Generated by Django 2.0.8 on 2020-07-14 02:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0057_trocacadastrador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trocacadastrador',
            old_name='usuario',
            new_name='alterado_por',
        ),
        migrations.RenameField(
            model_name='trocacadastrador',
            old_name='descricao',
            new_name='laudo',
        ),
        migrations.RemoveField(
            model_name='trocacadastrador',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='trocacadastrador',
            name='data_alteracao',
        ),
        migrations.RemoveField(
            model_name='trocacadastrador',
            name='situacao',
        ),
        migrations.AddField(
            model_name='trocacadastrador',
            name='alterado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Alterado em'),
        ),
        migrations.AddField(
            model_name='trocacadastrador',
            name='ente_federado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adesao.EnteFederado'),
        ),
        migrations.AddField(
            model_name='trocacadastrador',
            name='oficio',
            field=models.FileField(max_length=255, null=True, upload_to='oficio'),
        ),
        migrations.AddField(
            model_name='trocacadastrador',
            name='status',
            field=models.CharField(blank=True, choices=[(0, 'Pendente de Análise'), (1, 'Aprovado'), (2, 'Rejeitado')], max_length=1, null=True),
        ),
    ]
