# Generated by Django 2.0.8 on 2020-07-14 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0058_auto_20200713_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trocacadastrador',
            name='alterado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adesao.Usuario'),
        ),
    ]
