# Generated by Django 2.0.8 on 2020-07-17 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0060_auto_20200713_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='estado_expeditor',
            field=models.ForeignKey(choices=[(12, 'AC'), (27, 'AL'), (13, 'AM'), (16, 'AP'), (29, 'BA'), (23, 'CE'), (53, 'DF'), (32, 'ES'), (52, 'GO'), (21, 'MA'), (31, 'MG'), (50, 'MS'), (51, 'MT'), (15, 'PA'), (25, 'PB'), (26, 'PE'), (22, 'PI'), (41, 'PR'), (33, 'RJ'), (24, 'RN'), (11, 'RO'), (14, 'RR'), (43, 'RS'), (42, 'SC'), (28, 'SE'), (35, 'SP'), (17, 'TO')], on_delete=django.db.models.deletion.CASCADE, to='adesao.Uf'),
        ),
        migrations.AlterField(
            model_name='trocacadastrador',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Pendente de Análise'), ('1', 'Aprovado'), ('2', 'Rejeitado')], default='0', max_length=1, null=True),
        ),
    ]
