# Generated by Django 2.0.8 on 2020-07-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0060_auto_20200713_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trocacadastrador',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Pendente de Análise'), ('1', 'Aprovado'), ('2', 'Rejeitado')], default='0', max_length=1, null=True),
        ),
    ]
