# Generated by Django 2.0.8 on 2020-07-19 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0062_solicitacaodeadesao'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaodeadesao',
            name='avaliador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacao_avaliador', to='adesao.Usuario'),
        ),
        migrations.AddField(
            model_name='solicitacaodeadesao',
            name='data_analise',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Análise'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='situacao',
            field=models.CharField(blank=True, choices=[('0', 'Aguardando preenchimento dos dados cadastrais'), ('1', 'Aguardando envio da documentação'), ('2', 'Aguardando renovação da adesão'), ('3', 'Diligência Documental'), ('4', 'Aguardando análise do Plano de Trabalho'), ('5', 'Diligência Documental'), ('6', 'Publicado no DOU'), ('7', 'Acordo de Cooperação e Termo de Adesão aprovados')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sistemacultura',
            name='estado_processo',
            field=models.CharField(choices=[('0', 'Aguardando preenchimento dos dados cadastrais'), ('1', 'Aguardando envio da documentação'), ('2', 'Aguardando renovação da adesão'), ('3', 'Diligência Documental'), ('4', 'Aguardando análise do Plano de Trabalho'), ('5', 'Diligência Documental'), ('6', 'Publicado no DOU'), ('7', 'Acordo de Cooperação e Termo de Adesão aprovados')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='solicitacaodeadesao',
            name='alterado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacao_alterado_por', to='adesao.Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado_processo',
            field=models.CharField(choices=[('0', 'Aguardando preenchimento dos dados cadastrais'), ('1', 'Aguardando envio da documentação'), ('2', 'Aguardando renovação da adesão'), ('3', 'Diligência Documental'), ('4', 'Aguardando análise do Plano de Trabalho'), ('5', 'Diligência Documental'), ('6', 'Publicado no DOU'), ('7', 'Acordo de Cooperação e Termo de Adesão aprovados')], default='0', max_length=1),
        ),
    ]
