# Generated by Django 2.0.8 on 2020-07-27 15:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0063_auto_20200719_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoDeTrocaDeCadastrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('0', 'Pendente de Análise'), ('1', 'Aprovado'), ('2', 'Rejeitado')], default='0', max_length=1, null=True)),
                ('alterado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Alterado em')),
                ('oficio', models.FileField(max_length=255, null=True, upload_to='oficio')),
                ('laudo', models.TextField(blank=True, null=True)),
                ('data_analise', models.DateTimeField(blank=True, null=True, verbose_name='Data de Análise')),
                ('alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacaodetrocadecadastrador_alterado_por', to='adesao.Usuario')),
                ('avaliador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacaodetrocadecadastrador_avaliador', to='adesao.Usuario')),
                ('ente_federado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adesao.EnteFederado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='requerimentotrocacadastrador',
            name='ente_federado',
        ),
        migrations.RemoveField(
            model_name='trocacadastrador',
            name='alterado_por',
        ),
        migrations.RemoveField(
            model_name='trocacadastrador',
            name='ente_federado',
        ),
        migrations.AlterField(
            model_name='solicitacaodeadesao',
            name='alterado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacaodeadesao_alterado_por', to='adesao.Usuario'),
        ),
        migrations.AlterField(
            model_name='solicitacaodeadesao',
            name='avaliador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacaodeadesao_avaliador', to='adesao.Usuario'),
        ),
        migrations.DeleteModel(
            name='RequerimentoTrocaCadastrador',
        ),
        migrations.DeleteModel(
            name='TrocaCadastrador',
        ),
    ]
