# Generated by Django 2.0.8 on 2019-04-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_historicaldiligenciasimples'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldiligenciasimples',
            name='arquivo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
