# Generated by Django 2.0.8 on 2019-05-22 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0044_auto_20190507_1709'),
        ('gestao', '0010_historicaldiligenciasimples_arquivo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contatado', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('discussao', models.TextField()),
                ('contatante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='adesao.Usuario')),
                ('sistema_cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='adesao.SistemaCultura')),
            ],
        ),
    ]
