# Generated by Django 2.0.8 on 2019-07-24 20:20

from django.db import migrations
from adesao.models import Usuario
from django.contrib.auth.models import Group


def alterar_permissoes_gestores(apps, schema_editor):
    new_group, created = Group.objects.get_or_create(name='usuario_scdc')
    for usuario in Usuario.objects.filter(user__is_staff=True):
        new_group.user_set.add(usuario.user)


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0011_contato'),
    ]

    operations = [
        migrations.RunPython(alterar_permissoes_gestores)
    ]
